# Generated by Django 5.2.1 on 2025-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='tester', max_length=100),
            preserve_default=False,
        ),
    ]
