# Generated by Django 5.2.1 on 2025-06-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
